services:
  captcha-login:
    build:
      context: ./captcha-login
    ports:
      - "15000:5000"
    volumes:
      - ./captcha-login/export:/app/export
    restart: always
    depends_on:
      - ocr-service-easyocr
      - ocr-service-paddleocr

  ocr-service-easyocr:
    build:
      context: ./ocr-service-easyocr
    ports:
      - "16000:6000"
    restart: always

  ocr-service-paddleocr:
    build:
      context: ./ocr-service-paddleocr
    ports:
      - "6000:6000"
    restart: always
